spring.application.name=auth-service

server.port = 4005

jwt.secret=XD79M9AIAru5qMfjQrM9g0WA3VqrxlIRks8nkaQS1R0=

spring.datasource.url=jdbc:postgresql://patient-service-db:5432/db
spring.datasource.username=admin_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true