### update an extisting patient entity
PUT http://localhost:4004/api/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type:application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe updated",
  "email": "test_update@ex.com",
  "address": "123 main street",
  "dateOfBirth": "1996-10-13"
}